# add
alias ga='git add'
alias gaa='git add .'
# commit 
alias gcm='git commit'
alias gcmv='git commit -v'
alias gcmv!='git commit -v --amend'
alias gcmvn='git commit -v --no-edit'
alias gcmvn!='git commit -v --no-edit --amend'
alias gcmva='git commit -v -a'
alias gcmva!='git commit -v -a --amend'
alias gcman!='git commit -v -a --no-edit --amend'
alias gcmans!='git commit -v -a -s --no-edit --amend'
alias gcmam='git commit -a -m'
alias gcmsm='git commit -s -m'
alias gcmas='git commit -a -s'
alias gcmasm='git commit -a -s -m'
alias gcms='git commit -S'
alias gcmss='git commit -S -s'
alias gcmssm='git commit -S -s -m'
alias gcmmsg='git commit -m'
# pull
alias gpl='git pull'
alias gplrb='git pull --rebase'
alias gplrbv='git pull --rebase -v'
alias gplrba='git pull --rebase --autostash'
alias gplrbav='git pull --rebase --autostash -v'
alias gplrbupm='git pull --rebase origin $(git_main_branch)'
alias gplrbupmi='git pull --rebase=interactive origin $(git_main_branch)'
alias gplupm='git pull upstream $(git_main_branch)'
alias gplupc='git pull upstream $(git_current_branch)'
alias gploc='git pull origin "$(git_current_branch)"'
# push
alias gpsh='git push'
alias gpshd='git push --dry-run'
alias gpshf='git push --force-with-lease'
alias gpshf!='git push --force'
alias gpshoat='git push origin --all && git push origin --tags'
alias gpshu='git push upstream'
alias gpshv='git push -v'
alias gpshoc='git push origin "$(git_current_branch)"'
alias gpshup='git push --set-upstream origin $(git_current_branch)'
# log
alias glg='git log'
alias glgs='git log --stat'
alias glgsp='git log --stat -p'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glggm='git log --graph --max-count=10'
alias glgo='git log --oneline --decorate'
alias glgol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias glgols="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --stat"
alias glgod="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'"
alias glgods="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
alias glgola="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --all"
alias glgog='git log --oneline --decorate --graph'
alias glgoga='git log --oneline --decorate --graph --all'
alias glgglp="_git_log_prettily"
# merge
alias gm='git merge'
alias gmom='git merge origin/$(git_main_branch)'
alias gmtl='git mergetool --no-prompt'
alias gmtlvim='git mergetool --no-prompt --tool=vimdiff'
alias gmum='git merge upstream/$(git_main_branch)'
alias gma='git merge --abort'
# rebase
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbd='git rebase $(git_develop_branch)'
alias grbi='git rebase -i'
alias grbm='git rebase $(git_main_branch)'
alias grbom='git rebase origin/$(git_main_branch)'
alias grbo='git rebase --onto'
alias grbs='git rebase --skip'
# remote
alias gr='git remote'
alias gra='git remote add'
alias grmv='git remote rename'
alias grrm='git remote remove'
alias grset='git remote set-url'
alias grup='git remote update'
alias grv='git remote -v'# reset
alias grs='git reset'
alias grsh='git reset --hard'
alias grsoch='git reset origin/$(git_current_branch) --hard'
alias grsu='git reset --'
# stash# switch
alias gsw='git switch'
alias gswc='git switch -c'
alias gswm='git switch $(git_main_branch)'
alias gswd='git switch $(git_develop_branch)'
